Dev Compliance Requirements
XgridInc/xc3 pull request #79
Opened 2023-09-18 10:50 UTC by kashan-01

Link: https://github.com/XgridInc/xc3/issues/76

	[PS-1]
	- Crating PR to fulfill compliance requirements. Issues:
- Added WAFv2 ACLs.
- Cloudwatch Alarms.
- CPU utilization Monitoring and SSH.

This code fulfill compliance requirements to make infrastructure more secure. The infrastucture xc3 module is modified and in main.tf there are three resources added.

- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
- [x] Every function, interface, class has a comment describing what it does and input/output parameters

]

2023-09-18 12:58 UTC, yaseenzafar123 commented on infrastructure/modules/xc3/main.tf
> +  alarm_name          = "${var.namespace}-Xc3_CPU_Usage_Alarm"
Kindly change Xc3 to xc3. Please do the same for other as well in same file.

2023-09-18 12:58 UTC, yaseenzafar123 commented on infrastructure/modules/xc3/main.tf
> +  alarm_name          = "${var.namespace}-Xc3_CPU_Usage_Alarm"
Else LGTM

2023-09-19 12:32 UTC, mfaaraz commented
LGTM

2023-09-20 03:32 UTC, samanXgrid approved these changes
LGTM

2023-09-20 07:21 UTC, faheem-khau9 requested changes
Use standard naming convention

2023-09-20 07:21 UTC, faheem-khau9 commented on infrastructure/modules/xc3/main.tf
> +  metric_name        = "${var.namespace}-xc3_cpu_utilization"
```suggestion
  metric_name        = "${var.namespace}-cpu-utilization"
```

2023-09-20 07:21 UTC, faheem-khau9 commented on infrastructure/modules/xc3/main.tf
> +  alarm_name          = "${var.namespace}-xc3_cpu_usage_alarm"
```suggestion
  alarm_name          = "${var.namespace}-cpu-usage-alarm"
```

Let's not use the xc3 as it will be coming from the workspaces

2023-09-20 07:21 UTC, faheem-khau9 commented on infrastructure/modules/xc3/main.tf
> +   tags = merge(local.tags, tomap({ "Name" = "${var.namespace}-cpu_usage_alarm" }))
```suggestion
   tags = merge(local.tags, tomap({ "Name" = "${var.namespace}-cpu-usage-alarm" }))
```

2023-09-20 07:21 UTC, faheem-khau9 commented on infrastructure/modules/xc3/main.tf
> +  name  = "${var.namespace}_xc3_web_acl"
```suggestion
  name  = "${var.namespace}-web-acl"
```

2023-09-20 07:21 UTC, faheem-khau9 commented on infrastructure/modules/xc3/main.tf
> +    metric_name                = "${var.namespace}_xc3_web_acl"
```suggestion
    metric_name                = "${var.namespace}-web-acl"
```

2023-09-20 07:21 UTC, faheem-khau9 commented on infrastructure/modules/xc3/main.tf
> +     tags = merge(local.tags, tomap({ "Name" = "${var.namespace}-web_acl_waf" }))
```suggestion
     tags = merge(local.tags, tomap({ "Name" = "${var.namespace}-web-acl-waf" }))
```

2023-09-20 07:44 UTC, faheem-khau9 approved these changes
LGTM

2023-09-20 07:52 UTC, yaseenzafar123 approved these changes
LGTM

2023-09-20 07:53 UTC, merged